const userActivityStubs = [
  {
    "id": "11590739459",
    "type": "IssuesEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 191051391,
      "name": "redwoodjs/redwood",
      "url": "https://api.github.com/repos/redwoodjs/redwood"
    },
    "payload": {
      "action": "opened",
      "issue": {
        "url": "https://api.github.com/repos/redwoodjs/redwood/issues/140",
        "repository_url": "https://api.github.com/repos/redwoodjs/redwood",
        "labels_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/labels{/name}",
        "comments_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/comments",
        "events_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/events",
        "html_url": "https://github.com/redwoodjs/redwood/issues/140",
        "id": 569683913,
        "node_id": "MDU6SXNzdWU1Njk2ODM5MTM=",
        "number": 140,
        "title": "Show JS errors on FatalError page in dev mode.",
        "user": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "testUser1",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/testUser1",
            "html_url": "https://github.com/testUser1",
            "followers_url": "https://api.github.com/users/testUser1/followers",
            "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
            "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
            "organizations_url": "https://api.github.com/users/testUser1/orgs",
            "repos_url": "https://api.github.com/users/testUser1/repos",
            "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
            "received_events_url": "https://api.github.com/users/testUser1/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-24T07:43:19Z",
        "updated_at": "2020-02-24T07:43:19Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": ""
      }
    },
    "public": true,
    "created_at": "2020-02-24T07:43:19Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11590613162",
    "type": "IssueCommentEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 226986662,
      "name": "redwoodjs/tutorial",
      "url": "https://api.github.com/repos/redwoodjs/tutorial"
    },
    "payload": {
      "action": "created",
      "issue": {
        "url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23",
        "repository_url": "https://api.github.com/repos/redwoodjs/tutorial",
        "labels_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/labels{/name}",
        "comments_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/comments",
        "events_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/events",
        "html_url": "https://github.com/redwoodjs/tutorial/issues/23",
        "id": 567111251,
        "node_id": "MDU6SXNzdWU1NjcxMTEyNTE=",
        "number": 23,
        "title": "Add note about code splitting",
        "user": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "cannikin",
            "id": 300,
            "node_id": "MDQ6VXNlcjMwMA==",
            "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/cannikin",
            "html_url": "https://github.com/cannikin",
            "followers_url": "https://api.github.com/users/cannikin/followers",
            "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
            "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
            "organizations_url": "https://api.github.com/users/cannikin/orgs",
            "repos_url": "https://api.github.com/users/cannikin/repos",
            "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/cannikin/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-18T19:33:22Z",
        "updated_at": "2020-02-24T07:19:31Z",
        "closed_at": "2020-02-24T07:19:31Z",
        "author_association": "CONTRIBUTOR",
        "body": ""
      },
      "comment": {
        "url": "https://api.github.com/repos/redwoodjs/tutorial/issues/comments/590193676",
        "html_url": "https://github.com/redwoodjs/tutorial/issues/23#issuecomment-590193676",
        "issue_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23",
        "id": 590193676,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDE5MzY3Ng==",
        "user": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "created_at": "2020-02-24T07:19:31Z",
        "updated_at": "2020-02-24T07:19:31Z",
        "author_association": "CONTRIBUTOR",
        "body": "Closed by 2b9687bb8f9a020e3955c7eb0cb33ff958043598."
      }
    },
    "public": true,
    "created_at": "2020-02-24T07:19:32Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11490447452",
    "type": "CreateEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 210903466,
      "name": "redwoodjs/example-blog",
      "url": "https://api.github.com/repos/redwoodjs/example-blog"
    },
    "payload": {
      "ref": "tpw-page-loader",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Example Blog app written with Redwood",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2020-02-11T17:06:06Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11561360047",
    "type": "PushEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 191051391,
      "name": "redwoodjs/redwood",
      "url": "https://api.github.com/repos/redwoodjs/redwood"
    },
    "payload": {
      "push_id": 4655236475,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "15f1c70588fefa51100a2a8b1c3608332ad929c8",
      "before": "773863e38aea18969b63f6fd4f1450b1871d4ab8",
      "commits": [
        {
          "sha": "15f1c70588fefa51100a2a8b1c3608332ad929c8",
          "author": {
            "email": "tom@testUser1.com",
            "name": "Tom Preston-Werner"
          },
          "message": "Explain how to use Redwood Router outside Redwood.",
          "distinct": true,
          "url": "https://api.github.com/repos/redwoodjs/redwood/commits/15f1c70588fefa51100a2a8b1c3608332ad929c8"
        }
      ]
    },
    "public": true,
    "created_at": "2020-02-19T23:06:27Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    },
    "id": "11490450609",
    "type": "PullRequestEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 210903466,
      "name": "redwoodjs/example-blog",
      "url": "https://api.github.com/repos/redwoodjs/example-blog"
    },
    "payload": {
      "action": "opened",
      "number": 20,
      "pull_request": {
        "url": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20",
        "id": 373776132,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzczNzc2MTMy",
        "html_url": "https://github.com/redwoodjs/example-blog/pull/20",
        "diff_url": "https://github.com/redwoodjs/example-blog/pull/20.diff",
        "patch_url": "https://github.com/redwoodjs/example-blog/pull/20.patch",
        "issue_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/20",
        "number": 20,
        "state": "open",
        "locked": false,
        "title": "Add page loading spinner",
        "user": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "body": "",
        "created_at": "2020-02-11T17:06:25Z",
        "updated_at": "2020-02-11T17:06:25Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": null,
        "assignee": null,
        "assignees": [],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [],
        "milestone": null,
        "commits_url": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20/commits",
        "review_comments_url": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20/comments",
        "review_comment_url": "https://api.github.com/repos/redwoodjs/example-blog/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/20/comments",
        "statuses_url": "https://api.github.com/repos/redwoodjs/example-blog/statuses/9279147e3dff630f652aeb6219f78b41874e555a",
        "head": {
          "label": "redwoodjs:tpw-page-loader",
          "ref": "tpw-page-loader",
          "sha": "9279147e3dff630f652aeb6219f78b41874e555a",
          "user": {
            "login": "redwoodjs",
            "id": 45050444,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1MDUwNDQ0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/45050444?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/redwoodjs",
            "html_url": "https://github.com/redwoodjs",
            "followers_url": "https://api.github.com/users/redwoodjs/followers",
            "following_url": "https://api.github.com/users/redwoodjs/following{/other_user}",
            "gists_url": "https://api.github.com/users/redwoodjs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/redwoodjs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/redwoodjs/subscriptions",
            "organizations_url": "https://api.github.com/users/redwoodjs/orgs",
            "repos_url": "https://api.github.com/users/redwoodjs/repos",
            "events_url": "https://api.github.com/users/redwoodjs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/redwoodjs/received_events",
            "type": "Organization",
            "site_admin": false
          },
          "repo": {
            "id": 210903466,
            "node_id": "MDEwOlJlcG9zaXRvcnkyMTA5MDM0NjY=",
            "name": "example-blog",
            "full_name": "redwoodjs/example-blog",
            "private": false,
            "owner": {
              "login": "redwoodjs",
              "id": 45050444,
              "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1MDUwNDQ0",
              "avatar_url": "https://avatars3.githubusercontent.com/u/45050444?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/redwoodjs",
              "html_url": "https://github.com/redwoodjs",
              "followers_url": "https://api.github.com/users/redwoodjs/followers",
              "following_url": "https://api.github.com/users/redwoodjs/following{/other_user}",
              "gists_url": "https://api.github.com/users/redwoodjs/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/redwoodjs/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/redwoodjs/subscriptions",
              "organizations_url": "https://api.github.com/users/redwoodjs/orgs",
              "repos_url": "https://api.github.com/users/redwoodjs/repos",
              "events_url": "https://api.github.com/users/redwoodjs/events{/privacy}",
              "received_events_url": "https://api.github.com/users/redwoodjs/received_events",
              "type": "Organization",
              "site_admin": false
            },
            "html_url": "https://github.com/redwoodjs/example-blog",
            "description": "Example Blog app written with Redwood",
            "fork": false,
            "url": "https://api.github.com/repos/redwoodjs/example-blog",
            "forks_url": "https://api.github.com/repos/redwoodjs/example-blog/forks",
            "keys_url": "https://api.github.com/repos/redwoodjs/example-blog/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/redwoodjs/example-blog/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/redwoodjs/example-blog/teams",
            "hooks_url": "https://api.github.com/repos/redwoodjs/example-blog/hooks",
            "issue_events_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/events{/number}",
            "events_url": "https://api.github.com/repos/redwoodjs/example-blog/events",
            "assignees_url": "https://api.github.com/repos/redwoodjs/example-blog/assignees{/user}",
            "branches_url": "https://api.github.com/repos/redwoodjs/example-blog/branches{/branch}",
            "tags_url": "https://api.github.com/repos/redwoodjs/example-blog/tags",
            "blobs_url": "https://api.github.com/repos/redwoodjs/example-blog/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/redwoodjs/example-blog/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/redwoodjs/example-blog/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/redwoodjs/example-blog/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/redwoodjs/example-blog/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/redwoodjs/example-blog/languages",
            "stargazers_url": "https://api.github.com/repos/redwoodjs/example-blog/stargazers",
            "contributors_url": "https://api.github.com/repos/redwoodjs/example-blog/contributors",
            "subscribers_url": "https://api.github.com/repos/redwoodjs/example-blog/subscribers",
            "subscription_url": "https://api.github.com/repos/redwoodjs/example-blog/subscription",
            "commits_url": "https://api.github.com/repos/redwoodjs/example-blog/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/redwoodjs/example-blog/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/redwoodjs/example-blog/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/redwoodjs/example-blog/contents/{+path}",
            "compare_url": "https://api.github.com/repos/redwoodjs/example-blog/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/redwoodjs/example-blog/merges",
            "archive_url": "https://api.github.com/repos/redwoodjs/example-blog/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/redwoodjs/example-blog/downloads",
            "issues_url": "https://api.github.com/repos/redwoodjs/example-blog/issues{/number}",
            "pulls_url": "https://api.github.com/repos/redwoodjs/example-blog/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/redwoodjs/example-blog/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/redwoodjs/example-blog/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/redwoodjs/example-blog/labels{/name}",
            "releases_url": "https://api.github.com/repos/redwoodjs/example-blog/releases{/id}",
            "deployments_url": "https://api.github.com/repos/redwoodjs/example-blog/deployments",
            "created_at": "2019-09-25T17:33:35Z",
            "updated_at": "2020-02-11T09:17:48Z",
            "pushed_at": "2020-02-11T17:06:06Z",
            "git_url": "git://github.com/redwoodjs/example-blog.git",
            "ssh_url": "git@github.com:redwoodjs/example-blog.git",
            "clone_url": "https://github.com/redwoodjs/example-blog.git",
            "svn_url": "https://github.com/redwoodjs/example-blog",
            "homepage": "",
            "size": 5245,
            "stargazers_count": 6,
            "watchers_count": 6,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 2,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 3,
            "license": {
              "key": "mit",
              "name": "MIT License",
              "spdx_id": "MIT",
              "url": "https://api.github.com/licenses/mit",
              "node_id": "MDc6TGljZW5zZTEz"
            },
            "forks": 2,
            "open_issues": 3,
            "watchers": 6,
            "default_branch": "master"
          }
        },
        "base": {
          "label": "redwoodjs:master",
          "ref": "master",
          "sha": "220d3d3362461135553ebdb607b628a162af2e45",
          "user": {
            "login": "redwoodjs",
            "id": 45050444,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1MDUwNDQ0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/45050444?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/redwoodjs",
            "html_url": "https://github.com/redwoodjs",
            "followers_url": "https://api.github.com/users/redwoodjs/followers",
            "following_url": "https://api.github.com/users/redwoodjs/following{/other_user}",
            "gists_url": "https://api.github.com/users/redwoodjs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/redwoodjs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/redwoodjs/subscriptions",
            "organizations_url": "https://api.github.com/users/redwoodjs/orgs",
            "repos_url": "https://api.github.com/users/redwoodjs/repos",
            "events_url": "https://api.github.com/users/redwoodjs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/redwoodjs/received_events",
            "type": "Organization",
            "site_admin": false
          },
          "repo": {
            "id": 210903466,
            "node_id": "MDEwOlJlcG9zaXRvcnkyMTA5MDM0NjY=",
            "name": "example-blog",
            "full_name": "redwoodjs/example-blog",
            "private": false,
            "owner": {
              "login": "redwoodjs",
              "id": 45050444,
              "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1MDUwNDQ0",
              "avatar_url": "https://avatars3.githubusercontent.com/u/45050444?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/redwoodjs",
              "html_url": "https://github.com/redwoodjs",
              "followers_url": "https://api.github.com/users/redwoodjs/followers",
              "following_url": "https://api.github.com/users/redwoodjs/following{/other_user}",
              "gists_url": "https://api.github.com/users/redwoodjs/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/redwoodjs/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/redwoodjs/subscriptions",
              "organizations_url": "https://api.github.com/users/redwoodjs/orgs",
              "repos_url": "https://api.github.com/users/redwoodjs/repos",
              "events_url": "https://api.github.com/users/redwoodjs/events{/privacy}",
              "received_events_url": "https://api.github.com/users/redwoodjs/received_events",
              "type": "Organization",
              "site_admin": false
            },
            "html_url": "https://github.com/redwoodjs/example-blog",
            "description": "Example Blog app written with Redwood",
            "fork": false,
            "url": "https://api.github.com/repos/redwoodjs/example-blog",
            "forks_url": "https://api.github.com/repos/redwoodjs/example-blog/forks",
            "keys_url": "https://api.github.com/repos/redwoodjs/example-blog/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/redwoodjs/example-blog/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/redwoodjs/example-blog/teams",
            "hooks_url": "https://api.github.com/repos/redwoodjs/example-blog/hooks",
            "issue_events_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/events{/number}",
            "events_url": "https://api.github.com/repos/redwoodjs/example-blog/events",
            "assignees_url": "https://api.github.com/repos/redwoodjs/example-blog/assignees{/user}",
            "branches_url": "https://api.github.com/repos/redwoodjs/example-blog/branches{/branch}",
            "tags_url": "https://api.github.com/repos/redwoodjs/example-blog/tags",
            "blobs_url": "https://api.github.com/repos/redwoodjs/example-blog/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/redwoodjs/example-blog/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/redwoodjs/example-blog/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/redwoodjs/example-blog/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/redwoodjs/example-blog/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/redwoodjs/example-blog/languages",
            "stargazers_url": "https://api.github.com/repos/redwoodjs/example-blog/stargazers",
            "contributors_url": "https://api.github.com/repos/redwoodjs/example-blog/contributors",
            "subscribers_url": "https://api.github.com/repos/redwoodjs/example-blog/subscribers",
            "subscription_url": "https://api.github.com/repos/redwoodjs/example-blog/subscription",
            "commits_url": "https://api.github.com/repos/redwoodjs/example-blog/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/redwoodjs/example-blog/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/redwoodjs/example-blog/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/redwoodjs/example-blog/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/redwoodjs/example-blog/contents/{+path}",
            "compare_url": "https://api.github.com/repos/redwoodjs/example-blog/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/redwoodjs/example-blog/merges",
            "archive_url": "https://api.github.com/repos/redwoodjs/example-blog/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/redwoodjs/example-blog/downloads",
            "issues_url": "https://api.github.com/repos/redwoodjs/example-blog/issues{/number}",
            "pulls_url": "https://api.github.com/repos/redwoodjs/example-blog/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/redwoodjs/example-blog/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/redwoodjs/example-blog/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/redwoodjs/example-blog/labels{/name}",
            "releases_url": "https://api.github.com/repos/redwoodjs/example-blog/releases{/id}",
            "deployments_url": "https://api.github.com/repos/redwoodjs/example-blog/deployments",
            "created_at": "2019-09-25T17:33:35Z",
            "updated_at": "2020-02-11T09:17:48Z",
            "pushed_at": "2020-02-11T17:06:06Z",
            "git_url": "git://github.com/redwoodjs/example-blog.git",
            "ssh_url": "git@github.com:redwoodjs/example-blog.git",
            "clone_url": "https://github.com/redwoodjs/example-blog.git",
            "svn_url": "https://github.com/redwoodjs/example-blog",
            "homepage": "",
            "size": 5245,
            "stargazers_count": 6,
            "watchers_count": 6,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 2,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 3,
            "license": {
              "key": "mit",
              "name": "MIT License",
              "spdx_id": "MIT",
              "url": "https://api.github.com/licenses/mit",
              "node_id": "MDc6TGljZW5zZTEz"
            },
            "forks": 2,
            "open_issues": 3,
            "watchers": 6,
            "default_branch": "master"
          }
        },
        "_links": {
          "self": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20"
          },
          "html": {
            "href": "https://github.com/redwoodjs/example-blog/pull/20"
          },
          "issue": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/issues/20"
          },
          "comments": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/issues/20/comments"
          },
          "review_comments": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20/comments"
          },
          "review_comment": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/pulls/comments{/number}"
          },
          "commits": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/pulls/20/commits"
          },
          "statuses": {
            "href": "https://api.github.com/repos/redwoodjs/example-blog/statuses/9279147e3dff630f652aeb6219f78b41874e555a"
          }
        },
        "author_association": "CONTRIBUTOR",
        "merged": false,
        "mergeable": null,
        "rebaseable": null,
        "mergeable_state": "unknown",
        "merged_by": null,
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": false,
        "commits": 1,
        "additions": 31,
        "deletions": 1,
        "changed_files": 2
      }
    },
    "public": true,
    "created_at": "2020-02-11T17:06:25Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11572074709",
    "type": "DeleteEvent",
    "actor": {
      "id": 21,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/21?"
    },
    "repo": {
      "id": 201141978,
      "name": "manifold/tractor",
      "url": "https://api.github.com/repos/manifold/tractor"
    },
    "payload": {
      "ref": "clobber-studio-plugin-lib",
      "ref_type": "branch",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2020-02-20T23:01:47Z",
    "org": {
      "id": 17213336,
      "login": "manifold",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/manifold",
      "avatar_url": "https://avatars.githubusercontent.com/u/17213336?"
    }
  },
  {
    "id": "11577684074",
    "type": "ForkEvent",
    "actor": {
      "id": 21,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/21?"
    },
    "repo": {
      "id": 10582708,
      "name": "skratchdot/open-golang",
      "url": "https://api.github.com/repos/skratchdot/open-golang"
    },
    "payload": {
      "forkee": {
        "id": 242159347,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDIxNTkzNDc=",
        "name": "open-golang",
        "full_name": "testUser1/open-golang",
        "private": false,
        "owner": {
          "login": "testUser1",
          "id": 21,
          "node_id": "MDQ6VXNlcjIx",
          "avatar_url": "https://avatars3.githubusercontent.com/u/21?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/testUser1/open-golang",
        "description": "Open a file, directory, or URI using the OS's default application for that object type. Optionally, you can specify an application to use.",
        "fork": true,
        "url": "https://api.github.com/repos/testUser1/open-golang",
        "forks_url": "https://api.github.com/repos/testUser1/open-golang/forks",
        "keys_url": "https://api.github.com/repos/testUser1/open-golang/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/testUser1/open-golang/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/testUser1/open-golang/teams",
        "hooks_url": "https://api.github.com/repos/testUser1/open-golang/hooks",
        "issue_events_url": "https://api.github.com/repos/testUser1/open-golang/issues/events{/number}",
        "events_url": "https://api.github.com/repos/testUser1/open-golang/events",
        "assignees_url": "https://api.github.com/repos/testUser1/open-golang/assignees{/user}",
        "branches_url": "https://api.github.com/repos/testUser1/open-golang/branches{/branch}",
        "tags_url": "https://api.github.com/repos/testUser1/open-golang/tags",
        "blobs_url": "https://api.github.com/repos/testUser1/open-golang/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/testUser1/open-golang/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/testUser1/open-golang/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/testUser1/open-golang/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/testUser1/open-golang/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/testUser1/open-golang/languages",
        "stargazers_url": "https://api.github.com/repos/testUser1/open-golang/stargazers",
        "contributors_url": "https://api.github.com/repos/testUser1/open-golang/contributors",
        "subscribers_url": "https://api.github.com/repos/testUser1/open-golang/subscribers",
        "subscription_url": "https://api.github.com/repos/testUser1/open-golang/subscription",
        "commits_url": "https://api.github.com/repos/testUser1/open-golang/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/testUser1/open-golang/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/testUser1/open-golang/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/testUser1/open-golang/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/testUser1/open-golang/contents/{+path}",
        "compare_url": "https://api.github.com/repos/testUser1/open-golang/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/testUser1/open-golang/merges",
        "archive_url": "https://api.github.com/repos/testUser1/open-golang/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/testUser1/open-golang/downloads",
        "issues_url": "https://api.github.com/repos/testUser1/open-golang/issues{/number}",
        "pulls_url": "https://api.github.com/repos/testUser1/open-golang/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/testUser1/open-golang/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/testUser1/open-golang/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/testUser1/open-golang/labels{/name}",
        "releases_url": "https://api.github.com/repos/testUser1/open-golang/releases{/id}",
        "deployments_url": "https://api.github.com/repos/testUser1/open-golang/deployments",
        "created_at": "2020-02-21T14:34:55Z",
        "updated_at": "2020-02-21T11:55:10Z",
        "pushed_at": "2020-01-16T05:55:36Z",
        "git_url": "git://github.com/testUser1/open-golang.git",
        "ssh_url": "git@github.com:testUser1/open-golang.git",
        "clone_url": "https://github.com/testUser1/open-golang.git",
        "svn_url": "https://github.com/testUser1/open-golang",
        "homepage": null,
        "size": 19,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "public": true
      }
    },
    "public": true,
    "created_at": "2020-02-21T14:34:56Z"
  },
  {
    "id": "11571732742",
    "type": "WatchEvent",
    "actor": {
      "id": 21,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/21?"
    },
    "repo": {
      "id": 83050680,
      "name": "eclipse-theia/theia",
      "url": "https://api.github.com/repos/eclipse-theia/theia"
    },
    "payload": {
      "action": "started"
    },
    "public": true,
    "created_at": "2020-02-20T22:12:30Z",
    "org": {
      "id": 54183333,
      "login": "eclipse-theia",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/eclipse-theia",
      "avatar_url": "https://avatars.githubusercontent.com/u/54183333?"
    }
  },
]

export default userActivityStubs;