const userActivityStubs = [
  {
    "id": "11590739459",
    "type": "IssuesEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 191051391,
      "name": "redwoodjs/redwood",
      "url": "https://api.github.com/repos/redwoodjs/redwood"
    },
    "payload": {
      "action": "opened",
      "issue": {
        "url": "https://api.github.com/repos/redwoodjs/redwood/issues/140",
        "repository_url": "https://api.github.com/repos/redwoodjs/redwood",
        "labels_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/labels{/name}",
        "comments_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/comments",
        "events_url": "https://api.github.com/repos/redwoodjs/redwood/issues/140/events",
        "html_url": "https://github.com/redwoodjs/redwood/issues/140",
        "id": 569683913,
        "node_id": "MDU6SXNzdWU1Njk2ODM5MTM=",
        "number": 140,
        "title": "Show JS errors on FatalError page in dev mode.",
        "user": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "testUser1",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/testUser1",
            "html_url": "https://github.com/testUser1",
            "followers_url": "https://api.github.com/users/testUser1/followers",
            "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
            "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
            "organizations_url": "https://api.github.com/users/testUser1/orgs",
            "repos_url": "https://api.github.com/users/testUser1/repos",
            "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
            "received_events_url": "https://api.github.com/users/testUser1/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-24T07:43:19Z",
        "updated_at": "2020-02-24T07:43:19Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": ""
      }
    },
    "public": true,
    "created_at": "2020-02-24T07:43:19Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11590613178",
    "type": "IssuesEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 226986662,
      "name": "redwoodjs/tutorial",
      "url": "https://api.github.com/repos/redwoodjs/tutorial"
    },
    "payload": {
      "action": "closed",
      "issue": {
        "url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23",
        "repository_url": "https://api.github.com/repos/redwoodjs/tutorial",
        "labels_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/labels{/name}",
        "comments_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/comments",
        "events_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/events",
        "html_url": "https://github.com/redwoodjs/tutorial/issues/23",
        "id": 567111251,
        "node_id": "MDU6SXNzdWU1NjcxMTEyNTE=",
        "number": 23,
        "title": "Add note about code splitting",
        "user": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "cannikin",
            "id": 300,
            "node_id": "MDQ6VXNlcjMwMA==",
            "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/cannikin",
            "html_url": "https://github.com/cannikin",
            "followers_url": "https://api.github.com/users/cannikin/followers",
            "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
            "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
            "organizations_url": "https://api.github.com/users/cannikin/orgs",
            "repos_url": "https://api.github.com/users/cannikin/repos",
            "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/cannikin/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 1,
        "created_at": "2020-02-18T19:33:22Z",
        "updated_at": "2020-02-24T07:19:32Z",
        "closed_at": "2020-02-24T07:19:31Z",
        "author_association": "CONTRIBUTOR",
        "body": ""
      }
    },
    "public": true,
    "created_at": "2020-02-24T07:19:32Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  },
  {
    "id": "11590613162",
    "type": "IssueCommentEvent",
    "actor": {
      "id": 1,
      "login": "testUser1",
      "display_login": "testUser1",
      "gravatar_id": "",
      "url": "https://api.github.com/users/testUser1",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?"
    },
    "repo": {
      "id": 226986662,
      "name": "redwoodjs/tutorial",
      "url": "https://api.github.com/repos/redwoodjs/tutorial"
    },
    "payload": {
      "action": "created",
      "issue": {
        "url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23",
        "repository_url": "https://api.github.com/repos/redwoodjs/tutorial",
        "labels_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/labels{/name}",
        "comments_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/comments",
        "events_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23/events",
        "html_url": "https://github.com/redwoodjs/tutorial/issues/23",
        "id": 567111251,
        "node_id": "MDU6SXNzdWU1NjcxMTEyNTE=",
        "number": 23,
        "title": "Add note about code splitting",
        "user": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
          "login": "cannikin",
          "id": 300,
          "node_id": "MDQ6VXNlcjMwMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cannikin",
          "html_url": "https://github.com/cannikin",
          "followers_url": "https://api.github.com/users/cannikin/followers",
          "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
          "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
          "organizations_url": "https://api.github.com/users/cannikin/orgs",
          "repos_url": "https://api.github.com/users/cannikin/repos",
          "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cannikin/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "cannikin",
            "id": 300,
            "node_id": "MDQ6VXNlcjMwMA==",
            "avatar_url": "https://avatars1.githubusercontent.com/u/300?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/cannikin",
            "html_url": "https://github.com/cannikin",
            "followers_url": "https://api.github.com/users/cannikin/followers",
            "following_url": "https://api.github.com/users/cannikin/following{/other_user}",
            "gists_url": "https://api.github.com/users/cannikin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/cannikin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cannikin/subscriptions",
            "organizations_url": "https://api.github.com/users/cannikin/orgs",
            "repos_url": "https://api.github.com/users/cannikin/repos",
            "events_url": "https://api.github.com/users/cannikin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/cannikin/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-02-18T19:33:22Z",
        "updated_at": "2020-02-24T07:19:31Z",
        "closed_at": "2020-02-24T07:19:31Z",
        "author_association": "CONTRIBUTOR",
        "body": ""
      },
      "comment": {
        "url": "https://api.github.com/repos/redwoodjs/tutorial/issues/comments/590193676",
        "html_url": "https://github.com/redwoodjs/tutorial/issues/23#issuecomment-590193676",
        "issue_url": "https://api.github.com/repos/redwoodjs/tutorial/issues/23",
        "id": 590193676,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU5MDE5MzY3Ng==",
        "user": {
          "login": "testUser1",
          "id": 1,
          "node_id": "MDQ6VXNlcjE=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/testUser1",
          "html_url": "https://github.com/testUser1",
          "followers_url": "https://api.github.com/users/testUser1/followers",
          "following_url": "https://api.github.com/users/testUser1/following{/other_user}",
          "gists_url": "https://api.github.com/users/testUser1/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/testUser1/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/testUser1/subscriptions",
          "organizations_url": "https://api.github.com/users/testUser1/orgs",
          "repos_url": "https://api.github.com/users/testUser1/repos",
          "events_url": "https://api.github.com/users/testUser1/events{/privacy}",
          "received_events_url": "https://api.github.com/users/testUser1/received_events",
          "type": "User",
          "site_admin": false
        },
        "created_at": "2020-02-24T07:19:31Z",
        "updated_at": "2020-02-24T07:19:31Z",
        "author_association": "CONTRIBUTOR",
        "body": "Closed by 2b9687bb8f9a020e3955c7eb0cb33ff958043598."
      }
    },
    "public": true,
    "created_at": "2020-02-24T07:19:32Z",
    "org": {
      "id": 45050444,
      "login": "redwoodjs",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/redwoodjs",
      "avatar_url": "https://avatars.githubusercontent.com/u/45050444?"
    }
  }
]

export default userActivityStubs;